# Generated by Django 2.0 on 2018-06-13 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0002_ujian_id_ujian'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujian',
            name='is_akitf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ujian',
            name='id_ujian',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
