# Generated by Django 2.0 on 2018-06-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0004_kelasajar'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='kelas_ajar',
            field=models.ManyToManyField(through='sekolah.KelasAjar', to='sekolah.Kelas'),
        ),
    ]
