# Generated by Django 2.0 on 2018-06-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0005_guru_kelas_ajar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ujian',
            name='is_akitf',
        ),
    ]
