# Generated by Django 2.0 on 2018-06-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0006_remove_ujian_is_akitf'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujian',
            name='is_aktif',
            field=models.BooleanField(default=False),
        ),
    ]
