# Generated by Django 2.0 on 2018-06-20 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0007_ujian_is_aktif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelasajar',
            name='guru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelasajar', to='sekolah.Guru'),
        ),
        migrations.AlterField(
            model_name='kelasajar',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guruajar', to='sekolah.Kelas'),
        ),
    ]
